name: PRBlock-Stable

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - Stable

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:        
    - id: block-operation
      uses: actions/github-script@v7
      with:
        script: |
          echo "这个 PR 的目标分支是 Stable，该分支用于维护稳定版 PVZClass，不允许合并 PR。\n\n如果你尝试修复 2.x 版本的漏洞，请以 Stable-2.x 为目标分支重新开启 PR。"
          exit 1
